# Generated by Django 4.2.7 on 2026-01-27 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('input_text', models.TextField()),
                ('voice', models.CharField(choices=[('alloy', 'Alloy - Neutral'), ('echo', 'Echo - Male'), ('fable', 'Fable - British'), ('onyx', 'Onyx - Deep Male'), ('nova', 'Nova - Female'), ('shimmer', 'Shimmer - Soft Female')], default='alloy', max_length=50)),
                ('model', models.CharField(choices=[('tts-1', 'TTS-1 (Standard)'), ('tts-1-hd', 'TTS-1-HD (High Quality)')], default='tts-1', max_length=50)),
                ('speed', models.FloatField(default=1.0)),
                ('output_format', models.CharField(choices=[('mp3', 'MP3'), ('opus', 'Opus'), ('aac', 'AAC'), ('flac', 'FLAC'), ('wav', 'WAV'), ('pcm', 'PCM')], default='mp3', max_length=10)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='ai_voice/generations/')),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_size_bytes', models.IntegerField(blank=True, null=True)),
                ('characters_used', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Generation',
                'verbose_name_plural': 'Voice Generations',
                'db_table': 'ai_voice_voicegeneration',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('default_voice', models.CharField(default='alloy', max_length=50)),
                ('default_speed', models.FloatField(default=1.0)),
                ('default_model', models.CharField(default='tts-1', max_length=50)),
                ('total_characters_used', models.IntegerField(default=0)),
                ('total_generations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Voice Settings',
                'verbose_name_plural': 'User Voice Settings',
                'db_table': 'ai_voice_uservoicesettings',
            },
        ),
    ]
