# C:\Users\Trust computer\Desktop\Final_version_socialSync\posts\migrations\0001_initial.py
# Generated by Django 4.2.7 on 2025-12-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(help_text='Post caption/text')),
                ('ai_generated', models.BooleanField(default=False, help_text='Was caption AI-generated?')),
                ('media_files', models.TextField(default='[]', help_text='JSON array of media file paths')),
                ('scheduled_time', models.DateTimeField(help_text='When to post')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('platforms', models.TextField(default='[]', help_text='JSON array of platforms to post to')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('posting', 'Posting'), ('posted', 'Posted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('facebook_post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('twitter_post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('instagram_post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin_post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('tiktok_post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('youtube_post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('pinterest_post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('telegram_post_id', models.CharField(blank=True, max_length=200, null=True)),
                ('facebook_error', models.TextField(blank=True, null=True)),
                ('twitter_error', models.TextField(blank=True, null=True)),
                ('instagram_error', models.TextField(blank=True, null=True)),
                ('linkedin_error', models.TextField(blank=True, null=True)),
                ('tiktok_error', models.TextField(blank=True, null=True)),
                ('youtube_error', models.TextField(blank=True, null=True)),
                ('pinterest_error', models.TextField(blank=True, null=True)),
                ('telegram_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
