# Generated by Django 4.2.7 on 2026-02-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('posting', 'Posting'), ('posted', 'Posted'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
