# Generated by Django 4.2.7 on 2026-02-17 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0003_trendingcache_contentidea_engagement_tier_and_more'),
        ('posts', '0002_alter_post_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('all', 'All Platforms')], default='all', max_length=20)),
                ('variant_number', models.IntegerField(default=1)),
                ('body', models.TextField()),
                ('cta_text', models.CharField(blank=True, max_length=300)),
                ('tone', models.CharField(blank=True, max_length=100)),
                ('char_count', models.IntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_ab_test', models.BooleanField(default=False)),
                ('ab_label', models.CharField(blank=True, choices=[('A', 'Variant A'), ('B', 'Variant B')], max_length=1, null=True)),
                ('generation_prompt_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post Caption',
                'verbose_name_plural': 'Post Captions',
                'db_table': 'post_captions',
                'ordering': ['variant_number'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='angle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='post',
            name='checklist_status',
            field=models.JSONField(blank=True, default=dict, help_text='{"caption": true, "hashtags": false, "creative": false, "alt_text": false, "platform_mapping": false}'),
        ),
        migrations.AddField(
            model_name='post',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Call-to-action text', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='format_type',
            field=models.CharField(blank=True, choices=[('static', 'Static Image'), ('carousel', 'Carousel'), ('reel', 'Reel/Short'), ('thread', 'Thread'), ('story', 'Story'), ('text', 'Text Only')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='goal',
            field=models.CharField(blank=True, choices=[('leads', 'Lead Generation'), ('growth', 'Audience Growth'), ('authority', 'Thought Leadership')], max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='hook',
            field=models.TextField(blank=True, help_text='Post hook text'),
        ),
        migrations.AddField(
            model_name='post',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='brands.contentidea'),
        ),
        migrations.AddField(
            model_name='post',
            name='pillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='brands.contentpillar'),
        ),
        migrations.AddField(
            model_name='post',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScheduledPostPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('hashtag_placement', models.CharField(choices=[('inline', 'Inline'), ('end_of_caption', 'End of Caption'), ('first_comment', 'First Comment')], default='end_of_caption', max_length=20)),
                ('scheduled_at', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('publish_result_json', models.JSONField(blank=True, default=dict)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('caption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.postcaption')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_platform_posts', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_platforms', to='posts.post')),
            ],
            options={
                'verbose_name': 'Scheduled Post Platform',
                'verbose_name_plural': 'Scheduled Post Platforms',
                'db_table': 'scheduled_post_platforms',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('tag', models.CharField(help_text='Hashtag without #', max_length=200)),
                ('tier', models.CharField(choices=[('high_volume', 'High Volume (Reach)'), ('mid_volume', 'Mid Volume (Relevance)'), ('niche', 'Niche (Authority)')], default='mid_volume', max_length=20)),
                ('estimated_volume', models.IntegerField(default=0)),
                ('is_selected', models.BooleanField(default=True)),
                ('placement', models.CharField(choices=[('inline', 'Inline in Caption'), ('end_of_caption', 'End of Caption'), ('first_comment', 'First Comment (Instagram)')], default='end_of_caption', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post Hashtag',
                'verbose_name_plural': 'Post Hashtags',
                'db_table': 'post_hashtags',
                'ordering': ['tier', 'tag'],
            },
        ),
        migrations.AddField(
            model_name='postcaption',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='posts.post'),
        ),
        migrations.CreateModel(
            name='HashtagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tags', models.JSONField(default=list, help_text='Array of hashtag strings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_groups', to='brands.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hashtag Group',
                'verbose_name_plural': 'Hashtag Groups',
                'db_table': 'hashtag_groups',
            },
        ),
        migrations.CreateModel(
            name='BannedHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Hashtag without #', max_length=200)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_hashtags', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_hashtags', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Banned Hashtag',
                'verbose_name_plural': 'Banned Hashtags',
                'db_table': 'banned_hashtags',
                'unique_together': {('brand', 'tag')},
            },
        ),
    ]
