# Generated by Django 6.0.2 on 2026-02-24 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0004_imagegeneration_brand_template_and_more'),
        ('posts', '0003_postcaption_post_angle_post_approved_at_post_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpostplatform',
            name='asset_variant',
            field=models.ForeignKey(blank=True, help_text='Platform-specific resized creative asset', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_image.assetplatformvariant'),
        ),
    ]
