# Generated by Django 6.0.3 on 2026-04-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_postcaption_image_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('magic', 'Magic Link'), ('overflow', 'Overflow')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='When to post', null=True),
        ),
    ]
