# Generated by Django 6.0.3 on 2026-04-09 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_prompthistory'),
        ('posts', '0005_post_source_alter_post_scheduled_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicModeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params_hash', models.CharField(help_text='Encoded answer parameters (e.g., "2/2/1/123/6")', max_length=100)),
                ('post_ids', models.JSONField(default=list, help_text='List of Post IDs generated for this combination')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magic_caches', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magic Mode Cache',
                'verbose_name_plural': 'Magic Mode Caches',
                'db_table': 'magic_mode_cache',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'params_hash')},
            },
        ),
    ]
