# Generated by Django 5.2.14 on 2026-06-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_magic_draft_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption_generation_id',
            field=models.IntegerField(blank=True, help_text='ID of the CaptionGeneration record that produced this post caption', null=True),
        ),
    ]
