# Generated by Django 5.2.14 on 2026-06-13 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_add_caption_gen_id_and_shown_trending_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('author_name', models.CharField(default='User', max_length=200)),
                ('author_avatar', models.URLField(blank=True, null=True)),
                ('body', models.TextField()),
                ('sentiment', models.CharField(default='neutral', max_length=20)),
                ('created_at', models.DateTimeField()),
                ('reply_body', models.TextField(blank=True, null=True)),
                ('reply_type', models.CharField(blank=True, max_length=20, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
