# C:\Users\Trust computer\Desktop\Final_version_socialSync\messenger_bot\migrations\0001_initial.py
# Generated by Django 4.2.7 on 2025-12-24 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessengerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=255, unique=True)),
                ('page_name', models.CharField(max_length=255)),
                ('page_access_token', models.TextField()),
                ('verify_token', models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('is_webhook_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_reply_enabled', models.BooleanField(default=True)),
                ('greeting_text', models.TextField(default="Hi! I'm an AI assistant. How can I help you today?")),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Messenger Connection',
                'verbose_name_plural': 'Messenger Connections',
                'db_table': 'messenger_connections',
            },
        ),
        migrations.CreateModel(
            name='PDFKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='messenger_bot/pdfs/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing...'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_chunks', models.IntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('vectorized_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='messenger_bot.messengerconnection')),
            ],
            options={
                'verbose_name': 'PDF Knowledge Base',
                'verbose_name_plural': 'PDF Knowledge Bases',
                'db_table': 'pdf_knowledge_base',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField(default="You are a helpful AI assistant for a business. \nYou have access to company documents and product information through a knowledge base.\nProvide accurate, professional, and friendly responses based on the available knowledge.\nIf you don't know something, politely say so and offer to help in another way.\nKeep responses concise and helpful.", help_text='Define AI personality, role, and behavior')),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual & Friendly'), ('friendly', 'Warm & Friendly'), ('technical', 'Technical & Detailed'), ('sales', 'Sales-Oriented'), ('support', 'Customer Support')], default='friendly', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Only one prompt can be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='messenger_bot.messengerconnection')),
            ],
            options={
                'verbose_name': 'Custom Prompt',
                'verbose_name_plural': 'Custom Prompts',
                'db_table': 'custom_prompts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(db_index=True, max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_profile_pic', models.URLField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('message_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='messenger_bot.messengerconnection')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(max_length=255)),
                ('openai_model', models.CharField(choices=[('gpt-4o', 'GPT-4o (Best - Vision + Latest)'), ('gpt-4o-mini', 'GPT-4o Mini (Faster & Cheaper)'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo (Legacy)')], default='gpt-4o-mini', max_length=100)),
                ('embedding_model', models.CharField(choices=[('text-embedding-3-small', 'Text Embedding 3 Small (Recommended)'), ('text-embedding-3-large', 'Text Embedding 3 Large'), ('text-embedding-ada-002', 'Ada 002 (Legacy)')], default='text-embedding-3-small', max_length=100)),
                ('rag_enabled', models.BooleanField(default=True)),
                ('top_k_results', models.IntegerField(default=3, help_text='Number of relevant chunks to retrieve from knowledge base')),
                ('similarity_threshold', models.FloatField(default=0.7, help_text='Minimum similarity score (0-1) for RAG results')),
                ('temperature', models.FloatField(default=0.7, help_text='Creativity (0-2). Lower = focused, Higher = creative')),
                ('max_tokens', models.IntegerField(default=500, help_text='Maximum response length')),
                ('image_understanding_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='messenger_bot.messengerconnection')),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
                'db_table': 'ai_configurations',
            },
        ),
        migrations.CreateModel(
            name='PDFChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('embedding', models.TextField(help_text='JSON array of vector embeddings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='messenger_bot.pdfknowledgebase')),
            ],
            options={
                'verbose_name': 'PDF Chunk',
                'verbose_name_plural': 'PDF Chunks',
                'db_table': 'pdf_chunks',
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['pdf', 'chunk_index'], name='pdf_chunks_pdf_id_cb78d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('sticker', 'Sticker'), ('quick_reply', 'Quick Reply')], default='text', max_length=20)),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('rag_context_used', models.TextField(blank=True, help_text='Retrieved context from RAG', null=True)),
                ('prompt_used', models.TextField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0.0, help_text='Processing time in seconds')),
                ('image_description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger_bot.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['conversation', 'timestamp'], name='messages_convers_31a2d0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['connection', 'sender_id'], name='conversatio_connect_7a8e45_idx'),
        ),
    ]
