# Generated by Django 4.2.7 on 2026-02-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_bot', '0004_voice_settings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_connect_9fafc9_idx',
            old_name='notificatio_connect_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_connect_d84acb_idx',
            old_name='notificatio_connect_created_idx',
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='max_tokens',
            field=models.IntegerField(default=1500, help_text='Maximum response length (increased for complete responses)'),
        ),
    ]
