# Generated by Django 4.2.7 on 2026-02-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_bot', '0005_rename_notificatio_connect_idx_notificatio_connect_9fafc9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messengerconnection',
            name='website_url',
            field=models.URLField(blank=True, help_text='Website URL for AI knowledge extraction', null=True),
        ),
    ]
