# Generated by Django 4.2.7 on 2026-02-14 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_bot', '0006_add_website_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECommerceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type', models.CharField(choices=[('woocommerce', 'WooCommerce'), ('shopify', 'Shopify'), ('custom', 'Custom API')], default='woocommerce', max_length=20)),
                ('store_url', models.URLField(help_text='Store URL (e.g., https://yourstore.com)')),
                ('consumer_key', models.CharField(help_text='WooCommerce Consumer Key (ck_...)', max_length=255)),
                ('consumer_secret', models.CharField(help_text='WooCommerce Consumer Secret (cs_...)', max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('product_match_threshold', models.FloatField(default=0.35, help_text='Minimum similarity score for product matching (0-1)')),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_settings', to='messenger_bot.messengerconnection')),
            ],
            options={
                'verbose_name': 'E-Commerce Settings',
                'verbose_name_plural': 'E-Commerce Settings',
                'db_table': 'ecommerce_settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_product_id', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('regular_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('stock_status', models.CharField(default='instock', help_text='instock, outofstock, onbackorder', max_length=20)),
                ('stock_quantity', models.IntegerField(blank=True, null=True)),
                ('permalink', models.URLField(blank=True, max_length=500)),
                ('images', models.JSONField(default=list, help_text='[{id, src, name, alt}]')),
                ('categories', models.JSONField(default=list, help_text='[{id, name, slug}]')),
                ('embedding', models.TextField(blank=True, help_text='JSON array of vector embeddings for product matching', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('ecommerce_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='messenger_bot.ecommercesettings')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'ecommerce_products',
                'ordering': ['name'],
                'unique_together': {('ecommerce_settings', 'woo_product_id')},
            },
        ),
    ]
