# Generated by Django 4.2.7 on 2026-02-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_bot', '0007_ecommercesettings_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercesettings',
            name='consumer_key',
            field=models.CharField(blank=True, default='', help_text='WooCommerce Consumer Key (ck_...)', max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesettings',
            name='consumer_secret',
            field=models.CharField(blank=True, default='', help_text='WooCommerce Consumer Secret (cs_...)', max_length=255),
        ),
        migrations.AlterField(
            model_name='ecommercesettings',
            name='store_url',
            field=models.URLField(blank=True, default='', help_text='Store URL (e.g., https://yourstore.com)'),
        ),
    ]
