# Generated by Django 6.0.3 on 2026-05-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_bot', '0009_lower_similarity_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='similarity_threshold',
            field=models.FloatField(default=0.35, help_text='Minimum similarity score (0-1) for RAG results'),
        ),
    ]
