# Generated by Django 4.2.7 on 2026-02-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0002_fix_userimagesettings_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetPlatformVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('format_label', models.CharField(help_text='e.g. feed, story, reel', max_length=50)),
                ('file_url', models.ImageField(blank=True, null=True, upload_to='platform_variants/')),
                ('dimensions', models.CharField(help_text='e.g. 1080x1080', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset Platform Variant',
                'verbose_name_plural': 'Asset Platform Variants',
                'db_table': 'asset_platform_variants',
            },
        ),
        migrations.CreateModel(
            name='CreativeVersionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('file_url', models.ImageField(upload_to='creative_versions/')),
                ('generation_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Creative Version History',
                'verbose_name_plural': 'Creative Version Histories',
                'db_table': 'creative_version_history',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='alt_text',
            field=models.TextField(blank=True, help_text='Accessibility alt text (max 125 chars)'),
        ),
    ]
