# Generated by Django 4.2.7 on 2026-02-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0003_assetplatformvariant_creativeversionhistory_and_more'),
        ('brands', '0003_trendingcache_contentidea_engagement_tier_and_more'),
        ('posts', '0003_postcaption_post_angle_post_approved_at_post_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneration',
            name='brand_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.brandtemplate'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Is this the current version?'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creative_assets', to='posts.post'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='creativeversionhistory',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='ai_image.imagegeneration'),
        ),
        migrations.AddField(
            model_name='assetplatformvariant',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_variants', to='ai_image.imagegeneration'),
        ),
    ]
