# Generated by Django 6.0.3 on 2026-03-12 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0007_switch_to_gpt_image_model'),
        ('brands', '0008_prompthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneration',
            name='brand_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_generations', to='brands.brandasset'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='copy_text_in_image',
            field=models.CharField(blank=True, default='', help_text='Copy text rendered within the generated image', max_length=500),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='sibling_generation',
            field=models.ForeignKey(blank=True, help_text='Linked variation when with_copy=true', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sibling', to='ai_image.imagegeneration'),
        ),
        migrations.AddField(
            model_name='imagegeneration',
            name='with_copy',
            field=models.BooleanField(default=False, help_text='Whether copy text was rendered in the image by AI'),
        ),
        migrations.AlterField(
            model_name='imagegeneration',
            name='logo_position',
            field=models.CharField(choices=[('none', 'No Logo'), ('top_left', 'Top Left'), ('top_right', 'Top Right'), ('top_center', 'Top Center'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right'), ('bottom_center', 'Bottom Center'), ('center', 'Center')], default='bottom_right', max_length=20),
        ),
    ]
