# Generated by Django 6.0.3 on 2026-04-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_image', '0008_imagegeneration_brand_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagegeneration',
            name='style_metadata',
            field=models.JSONField(blank=True, help_text='Product style analysis data (colors, lighting, mood) for matching background generation', null=True),
        ),
    ]
