# Generated by Django 4.2.7 on 2026-02-14 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_alter_post_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('target_region', models.CharField(max_length=200)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/logos/')),
                ('brand_guide_pdf', models.FileField(blank=True, null=True, upload_to='brands/guides/')),
                ('voice_tone', models.CharField(default='professional', max_length=100)),
                ('do_dont_rules', models.JSONField(blank=True, default=dict)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('audiences', models.JSONField(blank=True, default=list)),
                ('brand_dna', models.JSONField(blank=True, default=dict)),
                ('brand_dna_generated_at', models.DateTimeField(blank=True, null=True)),
                ('brand_dna_source', models.CharField(blank=True, choices=[('website', 'Website Crawl'), ('pdf', 'Brand Guide PDF'), ('manual', 'Manual')], max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('team_size', models.IntegerField(blank=True, null=True)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('max_generations_per_day', models.IntegerField(default=200)),
                ('generations_today', models.IntegerField(default=0)),
                ('generation_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='LaunchPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_frequency', models.IntegerField(default=3, help_text='Posts per week')),
                ('formats_allowed', models.JSONField(blank=True, default=list)),
                ('variant_generation_level', models.CharField(choices=[('off', 'Off'), ('low', 'Low (1 variant)'), ('medium', 'Medium (2 variants)'), ('high', 'High (3 variants)')], default='medium', max_length=10)),
                ('approval_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='launch_plan', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Launch Plan',
                'verbose_name_plural': 'Launch Plans',
                'db_table': 'launch_plans',
            },
        ),
        migrations.CreateModel(
            name='ContentIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('hook', models.TextField(blank=True)),
                ('angle', models.CharField(blank=True, max_length=300)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('goal', models.CharField(blank=True, max_length=20)),
                ('content_format', models.CharField(choices=[('text', 'Text Post'), ('image', 'Image Post'), ('video', 'Video'), ('carousel', 'Carousel'), ('reel', 'Reel/Short'), ('thread', 'Thread'), ('story', 'Story')], default='text', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('persona', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('saved', 'Saved'), ('skipped', 'Skipped'), ('drafted', 'Converted to Draft'), ('scheduled', 'Linked to Calendar')], default='new', max_length=20)),
                ('batch_id', models.CharField(blank=True, max_length=50)),
                ('generation_run', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_ideas', to='brands.brand')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_ideas', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Idea',
                'verbose_name_plural': 'Content Ideas',
                'db_table': 'content_ideas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('compliance_checklist', models.JSONField(blank=True, default=dict)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='posts.post')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Approval',
                'verbose_name_plural': 'Content Approvals',
                'db_table': 'content_approvals',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='brands/assets/')),
                ('asset_type', models.CharField(choices=[('logo', 'Logo'), ('icon', 'Icon'), ('banner', 'Banner'), ('font', 'Font File'), ('color_palette', 'Color Palette'), ('template', 'Template'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Brand Asset',
                'verbose_name_plural': 'Brand Assets',
                'db_table': 'brand_assets',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='brands.workspace'),
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'db_table': 'weekly_reports',
                'ordering': ['-period_end'],
                'unique_together': {('brand', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='GenerationUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('idea', 'Idea Generation'), ('caption', 'Caption Generation'), ('image', 'Image Generation'), ('video', 'Video Generation'), ('brand_dna', 'Brand DNA Generation')], max_length=20)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_usage', to='brands.workspace')),
            ],
            options={
                'db_table': 'generation_usage',
                'unique_together': {('workspace', 'generation_type', 'date')},
            },
        ),
    ]
