# Generated by Django 4.2.7 on 2026-02-14 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDNAChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('source_url', models.URLField(max_length=2000)),
                ('page_title', models.CharField(blank=True, max_length=500)),
                ('embedding', models.TextField(help_text='JSON array of vector embeddings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_chunks', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Brand DNA Chunk',
                'verbose_name_plural': 'Brand DNA Chunks',
                'db_table': 'brand_dna_chunks',
                'ordering': ['chunk_index'],
                'indexes': [models.Index(fields=['brand', 'chunk_index'], name='brand_dna_c_brand_i_a12d71_idx')],
            },
        ),
    ]
