# Generated by Django 4.2.7 on 2026-02-17 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_post_status'),
        ('brands', '0002_branddnachunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('google', 'Google Trends')], max_length=20)),
                ('topic', models.CharField(max_length=500)),
                ('volume_score', models.FloatField(default=0)),
                ('region', models.CharField(default='global', max_length=100)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Trending Cache',
                'verbose_name_plural': 'Trending Cache',
                'db_table': 'trending_cache',
                'ordering': ['-volume_score'],
            },
        ),
        migrations.AddField(
            model_name='contentidea',
            name='engagement_tier',
            field=models.CharField(choices=[('low', 'Low'), ('mid', 'Mid'), ('high', 'High')], default='mid', max_length=10),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='metadata_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='source',
            field=models.CharField(choices=[('ai_generated', 'AI Generated'), ('trending', 'Trending Topic'), ('competitor_inspired', 'Competitor Inspired')], default='ai_generated', max_length=25),
        ),
        migrations.AddField(
            model_name='contentidea',
            name='trending_topic_ref',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='ab_test_results',
            field=models.JSONField(blank=True, default=list, help_text='A/B caption comparison results'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='best_hooks',
            field=models.JSONField(blank=True, default=list, help_text='Best performing hooks/angles'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='best_times',
            field=models.JSONField(blank=True, default=list, help_text='Best posting times'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='losers',
            field=models.JSONField(blank=True, default=list, help_text='Bottom performing posts'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='pillar_performance',
            field=models.JSONField(blank=True, default=dict, help_text='Actual vs target per pillar'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, help_text='LLM-generated recommendations'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='test_plan',
            field=models.JSONField(blank=True, default=list, help_text='Next week experiment suggestions'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='winners',
            field=models.JSONField(blank=True, default=list, help_text='Top performing posts [{post_id, metric, value}]'),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='brands.workspace'),
        ),
        migrations.CreateModel(
            name='ContentPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('target_percentage', models.IntegerField(default=0, help_text='Target % of content (0-100)')),
                ('color_code', models.CharField(default='#6366F1', help_text='Hex color for UI calendar', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pillars', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Content Pillar',
                'verbose_name_plural': 'Content Pillars',
                'db_table': 'content_pillars',
                'ordering': ['-target_percentage'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('handle_or_url', models.CharField(max_length=500)),
                ('last_crawled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_profiles', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Competitor Profile',
                'verbose_name_plural': 'Competitor Profiles',
                'db_table': 'competitor_profiles',
            },
        ),
        migrations.CreateModel(
            name='CompetitorInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_text', models.TextField()),
                ('angle', models.CharField(blank=True, max_length=200)),
                ('format_type', models.CharField(blank=True, max_length=50)),
                ('engagement_score', models.FloatField(default=0, help_text='Estimated engagement score')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('competitor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='brands.competitorprofile')),
            ],
            options={
                'verbose_name': 'Competitor Insight',
                'verbose_name_plural': 'Competitor Insights',
                'db_table': 'competitor_insights',
                'ordering': ['-engagement_score'],
            },
        ),
        migrations.CreateModel(
            name='BrandTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_file', models.FileField(blank=True, null=True, upload_to='brands/templates/')),
                ('logo_position', models.CharField(choices=[('top_left', 'Top Left'), ('top_right', 'Top Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right'), ('center', 'Center')], default='bottom_right', max_length=20)),
                ('font_family', models.CharField(blank=True, max_length=100)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_templates', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Brand Template',
                'verbose_name_plural': 'Brand Templates',
                'db_table': 'brand_templates',
            },
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected'), ('escalated', 'Escalated')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('off_brand', 'Off Brand'), ('compliance_issue', 'Compliance Issue'), ('quality', 'Quality'), ('factual_error', 'Factual Error'), ('timing', 'Timing'), ('other', 'Other')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='posts.post')),
            ],
            options={
                'verbose_name': 'Approval Log',
                'verbose_name_plural': 'Approval Logs',
                'db_table': 'approval_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentidea',
            name='pillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ideas', to='brands.contentpillar'),
        ),
        migrations.CreateModel(
            name='BestTimeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 6=Sunday')),
                ('hour_utc', models.IntegerField(help_text='Hour in UTC (0-23)')),
                ('score', models.FloatField(default=0, help_text='Engagement score')),
                ('source', models.CharField(choices=[('own_data', 'Own Analytics Data'), ('industry_default', 'Industry Default')], default='industry_default', max_length=20)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_time_suggestions', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Best Time Suggestion',
                'verbose_name_plural': 'Best Time Suggestions',
                'db_table': 'best_time_suggestions',
                'ordering': ['-score'],
                'unique_together': {('brand', 'platform', 'day_of_week', 'hour_utc')},
            },
        ),
    ]
