# Generated by Django 4.2.7 on 2026-02-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_trendingcache_contentidea_engagement_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorprofile',
            name='platform',
            field=models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('website', 'Website')], max_length=20),
        ),
    ]
