# Generated by Django 4.2.7 on 2026-02-21 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('brands', '0004_alter_competitorprofile_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentidea',
            name='media_preference',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='trendingcache',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_topics', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='trendingcache',
            name='relevance_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='OverflowProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=1)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('dna_completed', models.BooleanField(default=False)),
                ('pillars_completed', models.BooleanField(default=False)),
                ('competitors_completed', models.BooleanField(default=False)),
                ('trending_completed', models.BooleanField(default=False)),
                ('selected_idea_ids', models.JSONField(blank=True, default=list)),
                ('idea_media_preferences', models.JSONField(blank=True, default=dict)),
                ('selected_caption_ids', models.JSONField(blank=True, default=list)),
                ('generated_media_ids', models.JSONField(blank=True, default=list)),
                ('created_post_id', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='brands.brand')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overflow_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Overflow Progress',
                'verbose_name_plural': 'Overflow Progress',
                'db_table': 'overflow_progress',
            },
        ),
        migrations.CreateModel(
            name='BrandDNAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_data', models.JSONField(default=dict)),
                ('website_url', models.URLField(max_length=2000)),
                ('source', models.CharField(choices=[('website', 'Website'), ('pdf', 'PDF'), ('manual', 'Manual')], default='website', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_history', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Brand DNA History',
                'verbose_name_plural': 'Brand DNA Histories',
                'db_table': 'brand_dna_history',
                'ordering': ['-generated_at'],
            },
        ),
    ]
