# Generated by Django 5.2.14 on 2026-06-08 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_prompthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShownTrendingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shown_trending_topics', to='brands.brand')),
            ],
            options={
                'db_table': 'shown_trending_topics',
                'ordering': ['-shown_at'],
                'indexes': [models.Index(fields=['brand', 'shown_at'], name='shown_trend_brand_i_6fcf54_idx')],
            },
        ),
    ]
