# Generated by Django 4.2.7 on 2025-12-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('metric_type', models.CharField(choices=[('likes', 'Likes'), ('shares', 'Shares'), ('comments', 'Comments'), ('views', 'Views'), ('clicks', 'Clicks'), ('impressions', 'Impressions'), ('engagement_rate', 'Engagement Rate')], max_length=30)),
                ('metric_value', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics',
                'verbose_name_plural': 'Analytics',
                'db_table': 'analytics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', 'platform'], name='analytics_user_id_e4a682_idx'), models.Index(fields=['post', 'platform'], name='analytics_post_id_9189b3_idx')],
            },
        ),
    ]
