# Generated by Django 4.2.7 on 2026-02-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_branddnachunk'),
        ('posts', '0002_alter_post_status'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepurposedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repurpose_format', models.CharField(choices=[('carousel', 'Carousel'), ('thread', 'Thread'), ('reel', 'Reel'), ('email', 'Email'), ('blog_outline', 'Blog Outline')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repurposed_to', to='posts.post')),
                ('original_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repurposed_from', to='posts.post')),
            ],
            options={
                'verbose_name': 'Repurposed Content',
                'verbose_name_plural': 'Repurposed Content',
                'db_table': 'repurposed_content',
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('platform_comment_id', models.CharField(blank=True, max_length=200)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('author_handle', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=10)),
                ('replied', models.BooleanField(default=False)),
                ('reply_type', models.CharField(blank=True, choices=[('ai', 'AI Auto-Reply'), ('human', 'Human Reply')], max_length=10, null=True)),
                ('reply_body', models.TextField(blank=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post Comment',
                'verbose_name_plural': 'Post Comments',
                'db_table': 'post_comments',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('best_hook', 'Best Performing Hook'), ('best_time', 'Best Posting Time'), ('best_format', 'Best Content Format'), ('best_pillar', 'Best Content Pillar'), ('worst_hook', 'Worst Performing Hook'), ('worst_time', 'Worst Posting Time'), ('worst_format', 'Worst Content Format'), ('ab_winner', 'A/B Test Winner')], max_length=20)),
                ('reference_id', models.CharField(help_text='Post or caption ID', max_length=100)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('applied', models.BooleanField(default=False, help_text='Has this signal been used in generation?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_signals', to='brands.brand')),
            ],
            options={
                'verbose_name': 'Learning Signal',
                'verbose_name_plural': 'Learning Signals',
                'db_table': 'learning_signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20)),
                ('platform_post_id', models.CharField(blank=True, max_length=200)),
                ('snapshot_type', models.CharField(choices=[('24h', '24 Hour Snapshot'), ('48h', '48 Hour Snapshot'), ('daily', 'Daily Sync'), ('weekly', 'Weekly Aggregate')], max_length=10)),
                ('impressions', models.IntegerField(default=0)),
                ('reach', models.IntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('profile_visits', models.IntegerField(default=0)),
                ('data_json', models.JSONField(blank=True, default=dict, help_text='Platform-specific extra metrics')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_analytics', to='posts.post')),
            ],
            options={
                'verbose_name': 'Post Analytics',
                'verbose_name_plural': 'Post Analytics',
                'db_table': 'post_analytics',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['post', 'platform', 'snapshot_type'], name='post_analyt_post_id_55d7ad_idx')],
            },
        ),
    ]
