# Generated by Django 6.0.2 on 2026-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_repurposedcontent_postcomment_learningsignal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningsignal',
            name='signal_type',
            field=models.CharField(choices=[('best_hook', 'Best Performing Hook'), ('best_time', 'Best Posting Time'), ('best_format', 'Best Content Format'), ('best_pillar', 'Best Content Pillar'), ('worst_hook', 'Worst Performing Hook'), ('worst_time', 'Worst Posting Time'), ('worst_format', 'Worst Content Format'), ('ab_winner', 'A/B Test Winner'), ('winner', 'Winner Post')], max_length=20),
        ),
    ]
