# Generated by Django 4.2.7 on 2026-01-21 11:20

import ai_caption.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptionGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(blank=True, help_text='Topic or text to generate caption from', null=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=ai_caption.models.caption_media_path)),
                ('media_type', models.CharField(choices=[('none', 'Text Only'), ('image', 'Image'), ('video', 'Video')], default='none', max_length=10)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('enthusiastic', 'Enthusiastic'), ('humorous', 'Humorous'), ('inspirational', 'Inspirational'), ('formal', 'Formal'), ('conversational', 'Conversational')], default='professional', max_length=20)),
                ('length', models.CharField(choices=[('short', 'Short (20-40 words)'), ('medium', 'Medium (40-80 words)'), ('long', 'Long (80-120 words)'), ('extra_long', 'Extra Long (120-200 words)')], default='medium', max_length=20)),
                ('platform', models.CharField(choices=[('general', 'General'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest')], default='general', max_length=20)),
                ('include_hashtags', models.BooleanField(default=True)),
                ('include_emojis', models.BooleanField(default=True)),
                ('include_cta', models.BooleanField(default=True, verbose_name='Include Call-to-Action')),
                ('custom_instructions', models.TextField(blank=True, help_text='Additional instructions for AI', null=True)),
                ('generated_caption', models.TextField(blank=True, null=True)),
                ('generated_hashtags', models.TextField(blank=True, null=True)),
                ('media_analysis', models.TextField(blank=True, help_text='AI analysis of the media', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0, help_text='Processing time in seconds')),
                ('model_used', models.CharField(default='gpt-4o', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caption_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caption Generation',
                'verbose_name_plural': 'Caption Generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_openai_api_key', models.TextField(blank=True, db_column='openai_api_key', null=True)),
                ('default_model', models.CharField(choices=[('gpt-4o', 'GPT-4o (Best Quality)'), ('gpt-4o-mini', 'GPT-4o Mini (Faster & Cheaper)'), ('gpt-4-turbo', 'GPT-4 Turbo')], default='gpt-4o', max_length=50)),
                ('total_tokens_used', models.IntegerField(default=0)),
                ('total_generations', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User API Settings',
                'verbose_name_plural': 'User API Settings',
            },
        ),
        migrations.CreateModel(
            name='SavedCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_text', models.TextField()),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('used_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caption_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_caption.captiongeneration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_captions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, help_text='Available to all users')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('product', 'Product Launch'), ('promotion', 'Promotion/Sale'), ('event', 'Event'), ('announcement', 'Announcement'), ('engagement', 'Engagement'), ('educational', 'Educational'), ('behind_scenes', 'Behind the Scenes'), ('testimonial', 'Testimonial'), ('holiday', 'Holiday'), ('motivational', 'Motivational')], max_length=20)),
                ('template_text', models.TextField(help_text='Use {topic}, {brand}, {product} as placeholders')),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('friendly', 'Friendly'), ('enthusiastic', 'Enthusiastic'), ('humorous', 'Humorous'), ('inspirational', 'Inspirational'), ('formal', 'Formal'), ('conversational', 'Conversational')], default='professional', max_length=20)),
                ('platform', models.CharField(choices=[('general', 'General'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caption_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
