# Generated by Django 4.2.7 on 2026-01-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_caption', '0001_initial'),
    ]

    operations = [
    ]
