# Generated by Django 5.2.14 on 2026-06-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_caption', '0004_add_claude_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapisettings',
            name='default_claude_model',
            field=models.CharField(choices=[('claude-sonnet-4-6', 'Claude Sonnet 4.6 (Recommended)'), ('claude-haiku-4-5-20251001', 'Claude Haiku 4.5 (Faster & Cheaper)')], default='claude-sonnet-4-6', max_length=80),
        ),
    ]
