# Generated by Django 6.0.3 on 2026-05-10 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0008_prompthistory'),
        ('posts', '0007_post_magic_draft_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('meta', 'Meta (Facebook + Instagram)'), ('google', 'Google Ads')], max_length=10)),
                ('external_id', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('currency_code', models.CharField(blank=True, max_length=3)),
                ('timezone_name', models.CharField(blank=True, max_length=64)),
                ('encrypted_token', models.TextField(blank=True)),
                ('login_customer_id', models.CharField(blank=True, max_length=20)),
                ('business_id', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, help_text='Optional brand link — drives targeting suggestions from Brand DNA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_accounts', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_accounts',
            },
        ),
        migrations.CreateModel(
            name='AdAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('audience_type', models.CharField(choices=[('custom', 'Custom Audience'), ('lookalike', 'Lookalike Audience'), ('saved', 'Saved (rule-based) Audience')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('size_estimate', models.BigIntegerField(default=0)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('is_ready', models.BooleanField(default=False, help_text='Meta needs time to build custom audiences; false until ready.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='ads.adaccount')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_audiences', to='brands.brand')),
                ('source_audience', models.ForeignKey(blank=True, help_text='For lookalikes — the source custom audience.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_audiences', to='ads.adaudience')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_audiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_audiences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('objective', models.CharField(choices=[('traffic', 'Traffic / Link Clicks'), ('engagement', 'Engagement'), ('leads', 'Lead Generation'), ('sales', 'Sales / Conversions'), ('awareness', 'Brand Awareness'), ('boost_post', 'Boost Existing Post')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft (not yet sent to provider)'), ('pending_review', 'Pending Review (sent, ad under review)'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed (ran to end_date)'), ('disapproved', 'Disapproved'), ('failed', 'Failed (provider error)'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('external_campaign_id', models.CharField(blank=True, max_length=64)),
                ('external_adset_id', models.CharField(blank=True, max_length=64)),
                ('external_ad_id', models.CharField(blank=True, max_length=64)),
                ('external_creative_id', models.CharField(blank=True, max_length=64)),
                ('daily_budget_minor', models.BigIntegerField()),
                ('lifetime_budget_minor', models.BigIntegerField(blank=True, null=True)),
                ('spend_to_date_minor', models.BigIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('targeting_json', models.JSONField(blank=True, default=dict)),
                ('creative_json', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejection_codes', models.JSONField(blank=True, default=list)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='ads.adaccount')),
                ('boosted_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_boosts', to='posts.post')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('impressions', models.BigIntegerField(default=0)),
                ('reach', models.BigIntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('spend_minor', models.BigIntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('conversion_value_minor', models.BigIntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('cpc_minor', models.BigIntegerField(default=0)),
                ('cpm_minor', models.BigIntegerField(default=0)),
                ('frequency', models.FloatField(default=0.0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='ads.adcampaign')),
            ],
            options={
                'db_table': 'ad_insights',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='adaccount',
            index=models.Index(fields=['user', 'provider'], name='ad_accounts_user_id_839f19_idx'),
        ),
        migrations.AddIndex(
            model_name='adaccount',
            index=models.Index(fields=['brand'], name='ad_accounts_brand_i_b9a01b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adaccount',
            unique_together={('user', 'provider', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='adaudience',
            index=models.Index(fields=['user', '-created_at'], name='ad_audience_user_id_2ddf1a_idx'),
        ),
        migrations.AddIndex(
            model_name='adaudience',
            index=models.Index(fields=['brand', '-created_at'], name='ad_audience_brand_i_823ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['user', '-created_at'], name='ad_campaign_user_id_4e14b0_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['brand', '-created_at'], name='ad_campaign_brand_i_12128a_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['ad_account', 'status'], name='ad_campaign_ad_acco_28b106_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['external_campaign_id'], name='ad_campaign_externa_0aa005_idx'),
        ),
        migrations.AddIndex(
            model_name='adinsight',
            index=models.Index(fields=['campaign', '-date'], name='ad_insights_campaig_d3548d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adinsight',
            unique_together={('campaign', 'date')},
        ),
    ]
