# Generated by Django 5.2.14 on 2026-06-24 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
        ('brands', '0008_prompthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaignDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_type', models.CharField(default='search', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('suggestion', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaign_drafts', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaign_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_campaign_drafts',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'brand', '-updated_at'], name='ad_campaign_user_id_be5f80_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'brand', 'campaign_type'), name='uniq_draft_per_user_brand_type')],
            },
        ),
    ]
