# Generated by Django 5.2.14 on 2026-06-25 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_adcampaigndraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metric', models.CharField(choices=[('spend', 'Spend (last N days)'), ('cpc', 'Average CPC'), ('ctr', 'CTR'), ('conversions', 'Conversions'), ('cpa', 'Cost per conversion (CPA)')], max_length=20)),
                ('operator', models.CharField(choices=[('gt', '>'), ('lt', '<'), ('gte', '≥'), ('lte', '≤')], max_length=4)),
                ('threshold', models.FloatField()),
                ('lookback_days', models.IntegerField(default=7)),
                ('action', models.CharField(choices=[('pause', 'Pause the campaign'), ('notify', 'Notify only'), ('increase_budget', 'Increase daily budget by %'), ('decrease_budget', 'Decrease daily budget by %')], max_length=20)),
                ('action_value', models.FloatField(default=0, help_text='Percent for budget actions (e.g. 20 = ±20%).')),
                ('is_active', models.BooleanField(default=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='ads.adcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_rules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ad_rules_user_id_da9bb7_idx'), models.Index(fields=['is_active'], name='ad_rules_is_acti_059c9d_idx')],
            },
        ),
    ]
