# Generated by Django 5.2.14 on 2026-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_adrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccount',
            name='account_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adaccount',
            name='is_sandbox',
            field=models.BooleanField(default=False),
        ),
    ]
