# Generated by Django 5.2.14 on 2026-07-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_adaccount_account_status_adaccount_is_sandbox'),
        ('brands', '0009_add_caption_gen_id_and_shown_trending_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaudience',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Optional — audiences are account-scoped; brand is a hint.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_audiences', to='brands.brand'),
        ),
    ]
