# Generated by Django 4.2.7 on 2025-12-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Configuration key', max_length=100, unique=True)),
                ('value', models.TextField(blank=True, help_text='Configuration value')),
                ('description', models.CharField(blank=True, help_text='What this setting does', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
                'db_table': 'site_configuration',
                'ordering': ['key'],
            },
        ),
    ]
