# Generated by Django 4.2.7 on 2026-02-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_apiusagelog_and_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='captions_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='images_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_captions_per_month',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_images_per_month',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_messenger_messages',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_videos_per_month',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messenger_messages_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_duration_months',
            field=models.IntegerField(default=1, help_text='Plan duration in months'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='videos_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
