# Generated by Django 4.2.7 on 2026-02-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_captions_this_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('file', models.FileField(help_text='PDF file', upload_to='support_docs/')),
                ('extracted_text', models.TextField(blank=True, help_text='Auto-extracted text from PDF')),
                ('is_active', models.BooleanField(default=True, help_text='Include in chatbot knowledge')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support Knowledge Document',
                'verbose_name_plural': 'Support Knowledge Documents',
                'db_table': 'support_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
