# Generated by Django 4.2.7 on 2026-02-17 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_add_support_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('post_submitted', 'Post Submitted for Approval'), ('post_approved', 'Post Approved'), ('changes_requested', 'Changes Requested'), ('post_rejected', 'Post Rejected'), ('approval_reminder_12h', 'Approval Pending 12h'), ('approval_escalation_24h', 'Approval Escalated 24h'), ('post_scheduled', 'Post Scheduled'), ('post_published', 'Post Published'), ('publish_failed', 'Publish Failed'), ('captions_ready', 'Captions Generated'), ('images_ready', 'Images Generated'), ('video_rendering', 'Video Rendering Started'), ('video_ready', 'Video Ready'), ('batch_complete', 'Batch Complete'), ('weekly_report', 'Weekly Report Ready'), ('winner_detected', 'Winner Post Detected'), ('repurpose_suggestion', 'Repurpose Suggestion'), ('new_comment', 'New Comment on Post'), ('token_expiring', 'Platform Token Expiring'), ('daily_limit_warning', 'Daily Limit Approaching (80%)')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('data_json', models.JSONField(blank=True, default=dict, help_text='Additional context data')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('both', 'In-App + Email')], default='in_app', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Notification',
                'verbose_name_plural': 'System Notifications',
                'db_table': 'system_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='system_noti_user_id_013e73_idx'), models.Index(fields=['user', 'event_type'], name='system_noti_user_id_31ec73_idx')],
            },
        ),
    ]
