# Generated by Django 6.0.3 on 2026-03-10 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_roles_rbac'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotification',
            name='event_type',
            field=models.CharField(choices=[('post_submitted', 'Post Submitted for Approval'), ('post_approved', 'Post Approved'), ('changes_requested', 'Changes Requested'), ('post_rejected', 'Post Rejected'), ('approval_reminder_12h', 'Approval Pending 12h'), ('approval_escalation_24h', 'Approval Escalated 24h'), ('post_scheduled', 'Post Scheduled'), ('post_published', 'Post Published'), ('publish_failed', 'Publish Failed'), ('captions_ready', 'Captions Generated'), ('images_ready', 'Images Generated'), ('video_rendering', 'Video Rendering Started'), ('video_ready', 'Video Ready'), ('batch_complete', 'Batch Complete'), ('weekly_report', 'Weekly Report Ready'), ('winner_detected', 'Winner Post Detected'), ('repurpose_suggestion', 'Repurpose Suggestion'), ('new_comment', 'New Comment on Post'), ('token_expiring', 'Platform Token Expiring'), ('daily_limit_warning', 'Daily Limit Approaching (80%)'), ('reply_sla_breach', 'Reply SLA Breach')], max_length=30),
        ),
        migrations.CreateModel(
            name='DiamondWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, help_text='Current Diamond Token balance')),
                ('total_recharged', models.IntegerField(default=0, help_text='Lifetime diamonds received')),
                ('total_spent', models.IntegerField(default=0, help_text='Lifetime diamonds consumed')),
                ('last_recharge_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diamond_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diamond Wallet',
                'verbose_name_plural': 'Diamond Wallets',
                'db_table': 'diamond_wallets',
            },
        ),
        migrations.CreateModel(
            name='GlobalAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('claude', 'Anthropic Claude')], max_length=20, unique=True)),
                ('api_key', models.TextField(help_text='API key (stored securely)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global API Key',
                'verbose_name_plural': 'Global API Keys',
                'db_table': 'global_api_keys',
            },
        ),
        migrations.CreateModel(
            name='DiamondTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for recharge, negative for deduction')),
                ('transaction_type', models.CharField(choices=[('recharge', 'Recharge'), ('deduction', 'Deduction'), ('refund', 'Refund'), ('plan_grant', 'Plan Grant')], max_length=20)),
                ('balance_after', models.IntegerField(help_text='Wallet balance after this transaction')),
                ('feature', models.CharField(blank=True, default='', help_text='e.g. caption, image, video, voice, messenger', max_length=50)),
                ('provider', models.CharField(blank=True, default='', help_text='e.g. claude, openai, gemini', max_length=20)),
                ('raw_tokens', models.IntegerField(default=0, help_text='Actual API tokens used')),
                ('model_used', models.CharField(blank=True, default='', max_length=100)),
                ('raw_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diamond_recharges_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diamond_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diamond Transaction',
                'verbose_name_plural': 'Diamond Transactions',
                'db_table': 'diamond_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='diamond_tra_user_id_61cec8_idx'), models.Index(fields=['user', 'feature'], name='diamond_tra_user_id_87cc1f_idx'), models.Index(fields=['user', 'provider'], name='diamond_tra_user_id_dc887a_idx')],
            },
        ),
    ]
