# Generated by Django 6.0.2 on 2026-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_roles_rbac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemnotification',
            name='event_type',
            field=models.CharField(choices=[('post_submitted', 'Post Submitted for Approval'), ('post_approved', 'Post Approved'), ('changes_requested', 'Changes Requested'), ('post_rejected', 'Post Rejected'), ('approval_reminder_12h', 'Approval Pending 12h'), ('approval_escalation_24h', 'Approval Escalated 24h'), ('post_scheduled', 'Post Scheduled'), ('post_published', 'Post Published'), ('publish_failed', 'Publish Failed'), ('captions_ready', 'Captions Generated'), ('images_ready', 'Images Generated'), ('video_rendering', 'Video Rendering Started'), ('video_ready', 'Video Ready'), ('batch_complete', 'Batch Complete'), ('weekly_report', 'Weekly Report Ready'), ('winner_detected', 'Winner Post Detected'), ('repurpose_suggestion', 'Repurpose Suggestion'), ('new_comment', 'New Comment on Post'), ('token_expiring', 'Platform Token Expiring'), ('daily_limit_warning', 'Daily Limit Approaching (80%)'), ('reply_sla_breach', 'Reply SLA Breach')], max_length=30),
        ),
    ]
