# Generated by Django 6.0.2 on 2026-03-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_systemnotification_event_type'),
        ('accounts', '0008_alter_systemnotification_event_type_diamondwallet_and_more'),
    ]

    operations = [
    ]
