# Generated by Django 6.0.3 on 2026-03-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_encrypt_global_api_keys'),
        ('accounts', '0009_merge_20260311_0357'),
    ]

    operations = [
    ]
