# Generated by Django 6.0.2 on 2026-03-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_merge_20260316_0613'),
        ('accounts', '0010_merge_20260316_0614'),
    ]

    operations = [
    ]
