# Generated by Django 6.0.3 on 2026-04-12 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_unique_constraints_user_data_isolation'),
        ('accounts', '0011_merge_20260316_0811'),
    ]

    operations = [
    ]
