# Generated by Django 6.0.3 on 2026-05-05 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_merge_20260413_0406'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptOverrideAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(max_length=30)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('activate', 'Activate'), ('deactivate', 'Deactivate')], max_length=20)),
                ('previous_text', models.TextField(blank=True)),
                ('new_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prompt Override Audit Log',
                'verbose_name_plural': 'Prompt Override Audit Log',
                'db_table': 'prompt_override_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPromptOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('idea_system', 'Idea Generator — System'), ('idea_user', 'Idea Generator — User Context'), ('caption_system', 'Caption Generator — System'), ('image_refiner', 'Image Prompt Refiner'), ('brand_dna', 'Brand DNA Enhancer'), ('video_prompt', 'Video Prompt Builder')], max_length=30)),
                ('prompt_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Prompt Override',
                'verbose_name_plural': 'User Prompt Overrides',
                'db_table': 'user_prompt_overrides',
            },
        ),
        migrations.RemoveIndex(
            model_name='diamondtransaction',
            name='diamond_tx_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='systemnotification',
            name='sys_notif_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='user_role_ws_usr_idx',
        ),
        migrations.AlterField(
            model_name='globalapikey',
            name='api_key',
            field=models.TextField(blank=True, default='', help_text='Encrypted API key (Fernet)'),
        ),
        migrations.AddField(
            model_name='promptoverrideauditlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promptoverrideauditlog',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_audit_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpromptoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_overrides_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpromptoverride',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_overrides_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userpromptoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promptoverrideauditlog',
            name='override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='accounts.userpromptoverride'),
        ),
        migrations.AlterUniqueTogether(
            name='userpromptoverride',
            unique_together={('user', 'prompt_type')},
        ),
    ]
