# Generated by Django 6.0.3 on 2026-05-06 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_promptoverrideauditlog_userpromptoverride_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('card', 'Card (Stripe / 2C2P)'), ('paypal', 'PayPal'), ('crypto', 'Crypto'), ('other', 'Other')], max_length=20)),
                ('display_name', models.CharField(help_text='e.g. "Personal bKash" or "Sellanto Bank — DBBL"', max_length=100)),
                ('account_number', models.CharField(blank=True, default='', help_text='Phone, IBAN, merchant ID, etc.', max_length=120)),
                ('account_holder_name', models.CharField(blank=True, default='', max_length=120)),
                ('instructions', models.TextField(blank=True, default='', help_text='Free-form instructions shown to the user.')),
                ('currency', models.CharField(default='BDT', help_text='ISO code: BDT, USD, EUR, INR, …', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Payout Account',
                'verbose_name_plural': 'Admin Payout Accounts',
                'db_table': 'admin_payout_accounts',
                'ordering': ['sort_order', 'method'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(help_text='Target plan id (free/pro/business/...)', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, help_text='Plan list price in USD', max_digits=10)),
                ('amount_local', models.DecimalField(decimal_places=2, default=0, help_text='Amount the user actually paid in their currency', max_digits=12)),
                ('local_currency', models.CharField(default='BDT', max_length=10)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('card', 'Card (Stripe / 2C2P)'), ('paypal', 'PayPal'), ('crypto', 'Crypto'), ('other', 'Other')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, default='', help_text='bKash trxID, bank ref, card last-4, or a screenshot URL.', max_length=120)),
                ('payer_name', models.CharField(blank=True, default='', max_length=120)),
                ('payer_phone', models.CharField(blank=True, default='', max_length=40)),
                ('payer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('payer_notes', models.TextField(blank=True, default='', help_text='Optional message from the user.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('diamonds_granted', models.IntegerField(default=0)),
                ('plan_applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='accounts.adminpayoutaccount')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'db_table': 'payment_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='payment_req_user_id_bc089a_idx'), models.Index(fields=['status', 'created_at'], name='payment_req_status_373d5a_idx')],
            },
        ),
    ]
