# Generated by Django 6.0.3 on 2026-05-06 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_seed_payout_accounts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='fx_rate_used',
            field=models.DecimalField(decimal_places=8, default=0, help_text='1 local_currency = X USD, captured at approval', max_digits=20),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='revenue_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='amount_local converted to USD at approval time', max_digits=12),
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(default='USD', max_length=10)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('source', models.CharField(default='frankfurter', help_text='Provider that returned this rate', max_length=40)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FX Rate',
                'verbose_name_plural': 'FX Rates',
                'db_table': 'fx_rates',
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('server', 'Server / Hosting'), ('domain', 'Domain & SSL'), ('storage', 'Storage / CDN'), ('database', 'Database hosting'), ('email', 'Email service'), ('openai', 'OpenAI API'), ('gemini', 'Gemini API'), ('claude', 'Claude API'), ('other_api', 'Other API / SaaS'), ('marketing', 'Marketing / Ads'), ('payroll', 'Payroll / Contractors'), ('legal', 'Legal / Accounting'), ('other', 'Other')], max_length=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, help_text='Cost in USD', max_digits=12)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('incurred_on', models.DateField(help_text='Date the cost was incurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Entry',
                'verbose_name_plural': 'Expense Entries',
                'db_table': 'expense_entries',
                'ordering': ['-incurred_on', '-id'],
                'indexes': [models.Index(fields=['category', 'incurred_on'], name='expense_ent_categor_931443_idx'), models.Index(fields=['incurred_on'], name='expense_ent_incurre_0384b5_idx')],
            },
        ),
    ]
