# Generated by Django 6.0.3 on 2026-05-09 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_paymentrequest_fx_rate_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptoverrideauditlog',
            name='prompt_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpromptoverride',
            name='prompt_type',
            field=models.CharField(choices=[('idea_system', 'Ideas — System Prompt'), ('idea_user', 'Ideas — User Prompt'), ('idea_regenerate', 'Ideas — Regenerate (Feedback)'), ('caption_system', 'Caption — System Prompt'), ('caption_user', 'Caption — User Prompt'), ('caption_regenerate', 'Caption — Regenerate (Feedback)'), ('caption_adapt', 'Caption — Cross-Platform Adapt'), ('image_refiner', 'Image — Prompt Refiner'), ('image_product_bg', 'Image — Product Background'), ('image_product_smart', 'Image — Style-Matched Background'), ('video_prompt', 'Video — Prompt Builder'), ('brand_dna', 'Brand DNA — Registration Enrichment'), ('brand_dna_website', 'Brand DNA — Full Website Extraction'), ('brand_dna_manual', 'Brand DNA — Manual Input Enhancement'), ('trending_filter', 'Trending — Google Trends Filter'), ('competitor_analyze', 'Competitor — Crawl Analysis'), ('competitor_suggest', 'Competitor — Suggest'), ('pillars_generate', 'Content Pillars — Generate'), ('support_chat', 'Support — Chat System Prompt')], max_length=50),
        ),
        migrations.CreateModel(
            name='PromptExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(max_length=50)),
                ('was_override', models.BooleanField(default=False, help_text='True if an active UserPromptOverride was applied.')),
                ('prompt_sent', models.TextField(help_text='Exact prompt text sent to the LLM.')),
                ('response_received', models.TextField(blank=True, help_text='Raw text returned by the LLM.')),
                ('model_used', models.CharField(blank=True, max_length=80)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Execution',
                'verbose_name_plural': 'Prompt Executions',
                'db_table': 'prompt_executions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'prompt_type', '-created_at'], name='prompt_exec_user_id_4a2901_idx'), models.Index(fields=['user', '-created_at'], name='prompt_exec_user_id_5eda60_idx')],
            },
        ),
    ]
