# Generated by Django 6.0.3 on 2026-05-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_prompt_execution_extend_override_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='diamondtransaction',
            name='cache_read_tokens',
            field=models.IntegerField(default=0, help_text='Cached input tokens (90% discount on Anthropic)'),
        ),
        migrations.AddField(
            model_name='diamondtransaction',
            name='cache_write_tokens',
            field=models.IntegerField(default=0, help_text='Cache write tokens (1.25x cost on Anthropic)'),
        ),
        migrations.AddField(
            model_name='diamondtransaction',
            name='duration_seconds',
            field=models.IntegerField(default=0, help_text='Video duration in seconds (for video features)'),
        ),
        migrations.AddField(
            model_name='diamondtransaction',
            name='input_tokens',
            field=models.IntegerField(default=0, help_text='Exact input/prompt tokens from provider'),
        ),
        migrations.AddField(
            model_name='diamondtransaction',
            name='media_count',
            field=models.IntegerField(default=0, help_text='Image/video count for media features'),
        ),
        migrations.AddField(
            model_name='diamondtransaction',
            name='output_tokens',
            field=models.IntegerField(default=0, help_text='Exact output/completion tokens from provider'),
        ),
        migrations.AlterField(
            model_name='diamondtransaction',
            name='raw_tokens',
            field=models.IntegerField(default=0, help_text='Total API tokens (input + output)'),
        ),
    ]
