# Generated by Django 6.0.3 on 2026-05-13 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_userprofile_email_verified_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=64, unique=True)),
                ('default_payment_method_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stripe Customer',
                'verbose_name_plural': 'Stripe Customers',
                'db_table': 'stripe_customers',
            },
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=64, unique=True)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=64)),
                ('stripe_price_id', models.CharField(max_length=64)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('paused', 'Paused')], max_length=30)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stripe Subscription',
                'verbose_name_plural': 'Stripe Subscriptions',
                'db_table': 'stripe_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=64, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('ignored', 'Ignored')], default='ok', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
                'db_table': 'stripe_webhook_events',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='diamonds_topped_up',
            field=models.IntegerField(default=0, help_text='Diamonds added by a top-up purchase (separate from plan grant)'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='payment_provider',
            field=models.CharField(choices=[('manual', 'Manual (admin-verified)'), ('stripe', 'Stripe')], default='manual', help_text='Which gateway/flow created this row', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='purpose',
            field=models.CharField(choices=[('plan', 'Plan upgrade'), ('topup', 'Diamond top-up')], default='plan', help_text='plan = subscription purchase; topup = standalone diamond purchase', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='adminpayoutaccount',
            name='method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('card', 'Card (Stripe / 2C2P)'), ('paypal', 'PayPal'), ('crypto', 'Crypto'), ('stripe', 'Stripe'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('card', 'Card (Stripe / 2C2P)'), ('paypal', 'PayPal'), ('crypto', 'Crypto'), ('stripe', 'Stripe'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['payment_provider', 'purpose'], name='payment_req_payment_527ba4_idx'),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stripewebhookevent',
            index=models.Index(fields=['event_type', 'processed_at'], name='stripe_webh_event_t_fb8582_idx'),
        ),
        migrations.AddIndex(
            model_name='stripesubscription',
            index=models.Index(fields=['user', 'status'], name='stripe_subs_user_id_52a9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='stripesubscription',
            index=models.Index(fields=['stripe_customer_id'], name='stripe_subs_stripe__627faf_idx'),
        ),
    ]
