# Generated by Django 6.0.3 on 2026-05-13 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_stripecustomer_stripesubscription_stripewebhookevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=64, unique=True)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=64)),
                ('card_brand', models.CharField(blank=True, default='', max_length=20)),
                ('card_last4', models.CharField(blank=True, default='', max_length=4)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('card_funding', models.CharField(blank=True, default='', help_text='credit | debit | prepaid | unknown', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe Payment Method',
                'verbose_name_plural': 'Stripe Payment Methods',
                'db_table': 'stripe_payment_methods',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='stripe_paym_user_id_6a0070_idx')],
            },
        ),
    ]
