# Generated by Django 6.0.3 on 2026-05-13 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_emailotp_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='email_otps_user_id_e725d5_idx',
            old_name='email_otps_user_id_purpose_idx',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='refund_admin_notes',
            field=models.TextField(blank=True, default='', help_text="Admin's notes on approve/reject decision."),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='refund_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='USD amount refunded. v1 = always full amount.', max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='refund_processed_at',
            field=models.DateTimeField(blank=True, help_text='Set when charge.refunded webhook confirms the refund.', null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='refund_reason',
            field=models.TextField(blank=True, default='', help_text='User-supplied reason for the refund request.'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='refund_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='refund_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='refund_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('', 'Not requested'), ('requested', 'Requested by user'), ('approved', 'Approved by admin (refunding…)'), ('rejected', 'Rejected by admin'), ('processing', 'Sent to Stripe — awaiting confirmation'), ('refunded', 'Refunded'), ('failed', 'Refund attempt failed')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='stripe_refund_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='payment_provider',
            field=models.CharField(choices=[('manual', 'Manual (admin-verified)'), ('stripe', 'Stripe'), ('internal_wallet', 'Internal diamond wallet')], default='manual', help_text='Which gateway/flow created this row', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymentrequest',
            index=models.Index(fields=['refund_status', 'refund_requested_at'], name='payment_req_refund__94724c_idx'),
        ),
    ]
