# Generated by Django 5.2.14 on 2026-06-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_brand_dna_cost_bump'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='featurecostconfig',
            new_name='feature_cos_categor_c8feb2_idx',
            old_name='feature_cos_categor_b1ddc0_idx',
        ),
        migrations.RenameIndex(
            model_name='featurecostconfig',
            new_name='feature_cos_is_acti_4485a7_idx',
            old_name='feature_cos_is_acti_0ee75e_idx',
        ),
        migrations.AlterField(
            model_name='featurecostconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
