# video_studio/models.py

"""
SaleAnto Video Studio Models
Google Veo 3.1 AI Video Generation System
"""

import os
from django.db import models
from django.contrib.auth.models import User
from brands.models import Workspace, Brand


def project_upload_path(instance, filename):
    return f'video_studio/projects/{instance.user.id}/{instance.id}/{filename}'


def clip_video_path(instance, filename):
    return f'video_studio/clips/{instance.project.user.id}/{instance.project.id}/{filename}'


def clip_frame_path(instance, filename):
    return f'video_studio/frames/{instance.project.user.id}/{instance.project.id}/{filename}'


def merged_video_path(instance, filename):
    return f'video_studio/merged/{instance.project.user.id}/{instance.project.id}/{filename}'


def template_video_path(instance, filename):
    return f'video_studio/templates/{filename}'


class VideoProject(models.Model):
    """
    Main project container for video generation
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='video_projects')
    workspace = models.ForeignKey(Workspace, on_delete=models.CASCADE, null=True, blank=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True, blank=True)

    # Project details
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)

    # Product context
    product_images = models.JSONField(default=list)  # List of image paths/URLs
    product_name = models.CharField(max_length=200)
    product_description = models.TextField(blank=True)
    product_category = models.CharField(max_length=100, blank=True)

    # Generation settings
    target_platforms = models.JSONField(default=list)  # ['instagram', 'tiktok', 'amazon']
    default_aspect_ratio = models.CharField(max_length=10, default='16:9')
    default_resolution = models.CharField(max_length=10, default='1080p')
    auto_merge = models.BooleanField(default=False)

    # Status tracking
    STATUS_CHOICES = [
        ('draft', 'Draft'),
        ('generating', 'Generating Clips'),
        ('ready', 'Ready for Merge'),
        ('merging', 'Merging'),
        ('completed', 'Completed'),
        ('failed', 'Failed')
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='draft')
    progress = models.IntegerField(default=0)  # 0-100
    total_clips = models.IntegerField(default=0)
    completed_clips = models.IntegerField(default=0)

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'video_studio_projects'
        ordering = ['-created_at']
        verbose_name = 'Video Project'
        verbose_name_plural = 'Video Projects'

    def __str__(self):
        return f"{self.name} - {self.user.username}"

    def update_progress(self):
        """Calculate and update progress percentage"""
        if self.total_clips > 0:
            self.progress = int((self.completed_clips / self.total_clips) * 100)
        else:
            self.progress = 0
        self.save(update_fields=['progress'])

    def get_selected_clips(self):
        """Get clips selected for merging in order"""
        return self.clips.filter(is_selected=True).order_by('order_index')

    def calculate_total_cost(self):
        """Calculate total generation cost for all clips"""
        return sum(clip.generation_cost for clip in self.clips.all())


class VideoClip(models.Model):
    """
    Individual 8-second video clip generated by Veo
    """
    project = models.ForeignKey(VideoProject, on_delete=models.CASCADE, related_name='clips')

    # Input
    prompt = models.TextField(help_text="Original user prompt")
    enhanced_prompt = models.TextField(help_text="After BrandDNA injection")
    optimized_prompt = models.TextField(blank=True, help_text="After Gemini optimization")
    start_frame = models.ImageField(upload_to=clip_frame_path, blank=True, null=True)

    # Generation settings
    duration = models.IntegerField(default=8)
    ASPECT_RATIO_CHOICES = [
        ('16:9', 'Landscape (16:9)'),
        ('9:16', 'Portrait (9:16)'),
        ('1:1', 'Square (1:1)'),
        ('4:5', 'Instagram Portrait (4:5)'),
    ]
    aspect_ratio = models.CharField(max_length=10, choices=ASPECT_RATIO_CHOICES, default='16:9')

    RESOLUTION_CHOICES = [
        ('720p', '720p'),
        ('1080p', '1080p (Full HD)'),
        ('4k', '4K'),
    ]
    resolution = models.CharField(max_length=10, choices=RESOLUTION_CHOICES, default='1080p')

    style = models.CharField(max_length=50, default='cinematic')

    # Veo-specific parameters
    veo_model_used = models.CharField(max_length=50, blank=True, help_text="veo-3.1-generate-preview, etc.")
    veo_seed = models.IntegerField(null=True, blank=True, help_text="For reproducibility")
    camera_movement = models.CharField(max_length=100, blank=True, help_text="dolly, crane, orbit, etc.")
    lighting_style = models.CharField(max_length=100, blank=True)

    # Output
    video_file = models.FileField(upload_to=clip_video_path, blank=True, null=True)
    thumbnail = models.ImageField(upload_to=clip_frame_path, blank=True, null=True)
    audio_included = models.BooleanField(default=True)

    # Metadata
    file_size = models.BigIntegerField(default=0, help_text="File size in bytes")
    fps = models.IntegerField(default=30)
    codec = models.CharField(max_length=20, default='h264')

    # Selection for merging
    is_selected = models.BooleanField(default=False)
    order_index = models.IntegerField(default=0, help_text="Order in merged video")

    # Status
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed')
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    error_message = models.TextField(blank=True, null=True)
    processing_time = models.FloatField(default=0, help_text="Seconds")
    generation_cost = models.DecimalField(max_digits=10, decimal_places=2, default=0, help_text="USD")

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'video_studio_clips'
        ordering = ['order_index', '-created_at']
        verbose_name = 'Video Clip'
        verbose_name_plural = 'Video Clips'

    def __str__(self):
        return f"Clip {self.id} - {self.project.name} ({self.status})"

    def get_video_url(self):
        """Get video file URL if exists"""
        if self.video_file:
            return self.video_file.url
        return None

    def get_thumbnail_url(self):
        """Get thumbnail URL if exists"""
        if self.thumbnail:
            return self.thumbnail.url
        return None

    def mark_completed(self, video_data, processing_time, cost, model_used):
        """Mark clip as completed and update stats"""
        self.status = 'completed'
        self.processing_time = processing_time
        self.generation_cost = cost
        self.veo_model_used = model_used
        self.file_size = len(video_data) if video_data else 0
        self.save()

        # Update project progress
        self.project.completed_clips += 1
        self.project.update_progress()


class MergedVideo(models.Model):
    """
    Final merged video output from multiple clips
    """
    project = models.ForeignKey(VideoProject, on_delete=models.CASCADE, related_name='merged_videos')

    # Input clips (ordered)
    clip_ids = models.JSONField(default=list, help_text="List of clip IDs in order")

    # Merge settings
    TRANSITION_CHOICES = [
        ('cut', 'Hard Cut'),
        ('crossfade', 'Crossfade'),
        ('wipe', 'Wipe'),
        ('slide', 'Slide'),
        ('zoom', 'Zoom Transition')
    ]
    transition_type = models.CharField(max_length=20, choices=TRANSITION_CHOICES, default='crossfade')
    transition_duration = models.FloatField(default=0.5, help_text="Seconds")

    # Output
    merged_video = models.FileField(upload_to=merged_video_path)
    thumbnail = models.ImageField(upload_to=merged_video_path, blank=True, null=True)

    # Metadata
    total_duration = models.FloatField(default=0, help_text="Total duration in seconds")
    file_size = models.BigIntegerField(default=0, help_text="File size in bytes")
    resolution = models.CharField(max_length=10)
    aspect_ratio = models.CharField(max_length=10)

    # Captions/Overlays
    has_captions = models.BooleanField(default=False)
    captions_data = models.JSONField(default=list, blank=True, help_text="Caption timing and text")

    # Music/Audio
    background_music = models.FileField(upload_to='video_studio/music/', blank=True, null=True)
    music_volume = models.FloatField(default=0.3, help_text="Volume level 0-1")

    # Status
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed')
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    error_message = models.TextField(blank=True, null=True)
    processing_time = models.FloatField(default=0, help_text="Merge processing time in seconds")

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'video_studio_merged_videos'
        ordering = ['-created_at']
        verbose_name = 'Merged Video'
        verbose_name_plural = 'Merged Videos'

    def __str__(self):
        return f"Merged Video - {self.project.name} ({len(self.clip_ids)} clips)"

    def get_video_url(self):
        """Get merged video URL"""
        if self.merged_video:
            return self.merged_video.url
        return None

    def get_clips(self):
        """Get actual clip objects in order"""
        clips = []
        for clip_id in self.clip_ids:
            try:
                clip = VideoClip.objects.get(id=clip_id)
                clips.append(clip)
            except VideoClip.DoesNotExist:
                continue
        return clips


class PromptOptimizationLog(models.Model):
    """
    Track prompt optimizations for learning and improvement
    """
    project = models.ForeignKey(VideoProject, on_delete=models.CASCADE, null=True, blank=True)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, null=True, blank=True)

    original_prompt = models.TextField()
    optimized_prompt = models.TextField()
    optimization_model = models.CharField(max_length=50, help_text="gemini-2.5-pro, etc.")

    # Enhancement details
    enhancement_type = models.CharField(max_length=50, blank=True, help_text="brand_dna, gemini, template")
    enhancement_data = models.JSONField(default=dict, blank=True)

    # Results tracking
    video_quality_score = models.FloatField(null=True, blank=True, help_text="1-10 scale")
    user_rating = models.IntegerField(null=True, blank=True, help_text="1-5 stars")
    was_regenerated = models.BooleanField(default=False, help_text="Did user regenerate?")

    # Performance metrics
    views = models.IntegerField(default=0)
    engagement_rate = models.FloatField(default=0)
    conversion_rate = models.FloatField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'video_studio_prompt_logs'
        ordering = ['-created_at']
        verbose_name = 'Prompt Optimization Log'
        verbose_name_plural = 'Prompt Optimization Logs'

    def __str__(self):
        return f"Optimization {self.id} - {self.optimization_model}"


class VideoTemplate(models.Model):
    """
    Reusable video templates for common use cases
    """
    name = models.CharField(max_length=200)
    description = models.TextField()

    CATEGORY_CHOICES = [
        ('product_launch', 'Product Launch'),
        ('social_ad', 'Social Media Ad'),
        ('unboxing', 'Unboxing Experience'),
        ('showcase', 'Product Showcase'),
        ('lifestyle', 'Lifestyle Video'),
        ('testimonial', 'Testimonial'),
        ('tutorial', 'Tutorial/How-To'),
        ('comparison', 'Product Comparison'),
    ]
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES)

    # Template configuration
    clips_config = models.JSONField(default=list, help_text="List of clip configurations")
    """
    Example clips_config:
    [
        {
            'type': 'hero_reveal',
            'duration': 8,
            'prompt': 'Dramatic product reveal with dynamic lighting',
            'camera_movement': 'dolly_in',
            'lighting': 'dramatic'
        },
        {
            'type': '360_rotation',
            'duration': 8,
            'prompt': 'Smooth 360° orbit around product',
            'camera_movement': 'orbit',
            'lighting': 'studio'
        }
    ]
    """

    transition_type = models.CharField(max_length=20, default='crossfade')
    recommended_duration = models.IntegerField(help_text="Total recommended duration in seconds")
    aspect_ratio = models.CharField(max_length=10, default='16:9')

    # Availability
    is_global = models.BooleanField(default=False, help_text="Available to all users")
    is_active = models.BooleanField(default=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    # Preview
    preview_video = models.FileField(upload_to=template_video_path, blank=True, null=True)
    preview_thumbnail = models.ImageField(upload_to=template_video_path, blank=True, null=True)

    # Usage stats
    times_used = models.IntegerField(default=0)
    avg_rating = models.FloatField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'video_studio_templates'
        ordering = ['-times_used', 'name']
        verbose_name = 'Video Template'
        verbose_name_plural = 'Video Templates'

    def __str__(self):
        return f"{self.name} ({self.category})"

    def increment_usage(self):
        """Increment usage counter"""
        self.times_used += 1
        self.save(update_fields=['times_used'])

    def update_rating(self, new_rating):
        """Update average rating with new rating"""
        if self.avg_rating == 0:
            self.avg_rating = new_rating
        else:
            # Simple moving average
            self.avg_rating = (self.avg_rating * 0.9) + (new_rating * 0.1)
        self.save(update_fields=['avg_rating'])


class ABTestVariant(models.Model):
    """
    A/B testing variants for video optimization
    """
    project = models.ForeignKey(VideoProject, on_delete=models.CASCADE, related_name='ab_variants')
    clip = models.ForeignKey(VideoClip, on_delete=models.CASCADE, related_name='variants')

    variant_name = models.CharField(max_length=100, help_text="Variant A, B, C, etc.")
    variant_config = models.JSONField(default=dict, help_text="Variant-specific settings")

    # Performance metrics
    views = models.IntegerField(default=0)
    clicks = models.IntegerField(default=0)
    engagement_rate = models.FloatField(default=0)
    conversion_rate = models.FloatField(default=0)
    watch_time_avg = models.FloatField(default=0, help_text="Average watch time in seconds")

    # Results
    is_winner = models.BooleanField(default=False)
    confidence_score = models.FloatField(default=0, help_text="Statistical confidence 0-1")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'video_studio_ab_variants'
        ordering = ['-engagement_rate']
        verbose_name = 'A/B Test Variant'
        verbose_name_plural = 'A/B Test Variants'

    def __str__(self):
        return f"{self.variant_name} - {self.project.name}"

    def calculate_score(self):
        """Calculate composite performance score"""
        return (
            (self.engagement_rate * 0.3) +
            (self.conversion_rate * 0.4) +
            (min(self.watch_time_avg / 8.0, 1.0) * 0.3)  # Normalize to 8s
        )
