import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  TrashIcon,
  PencilIcon,
  SparklesIcon,
  MagnifyingGlassIcon,
} from '@heroicons/react/24/outline';
import { format } from 'date-fns';
import { postService } from '../../services/postService';
import type { Post, PlatformType } from '../../types';

const platformEmoji: Record<string, string> = {
  linkedin: '💼', instagram: '📸', facebook: '📘', twitter: '🐦', tiktok: '🎵',
};

export function MagicDraftPage() {
  const navigate = useNavigate();
  const [drafts, setDrafts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [deletingId, setDeletingId] = useState<number | null>(null);

  const fetchDrafts = async () => {
    setLoading(true);
    try {
      const result = await postService.list({ status: 'draft', source: 'magic', page_size: 100 });
      setDrafts(result.results || []);
    } catch {
      // Silent
    }
    setLoading(false);
  };

  useEffect(() => {
    fetchDrafts();
  }, []);

  const handleDelete = async (id: number) => {
    setDeletingId(id);
    try {
      await postService.delete(id);
      setDrafts(drafts.filter((d) => d.id !== id));
    } catch {
      // Silent
    }
    setDeletingId(null);
  };

  const handleEdit = (id: number) => {
    navigate(`/posts/${id}/edit`);
  };

  const filtered = drafts.filter((d) => {
    if (!searchQuery) return true;
    const q = searchQuery.toLowerCase();
    return (
      d.caption?.toLowerCase().includes(q) ||
      d.hook?.toLowerCase().includes(q)
    );
  });

  return (
    <div className="p-6 max-w-[900px] mx-auto">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <SparklesIcon className="w-7 h-7" style={{ color: 'rgb(var(--c-coral))' }} />
          <h1 className="text-[28px] font-black text-text-primary">Magic Link Drafts</h1>
        </div>
        <p className="text-[15px] text-text-secondary">
          Unpublished posts generated by Magic Link. Edit, publish, or delete them.
        </p>
      </div>

      {/* Stats */}
      <div
        className="rounded-[14px] p-4 flex items-center gap-4 mb-6"
        style={{ background: 'rgba(232,54,79,0.06)', border: '1px solid rgba(232,54,79,0.15)' }}
      >
        <div className="text-[32px] font-black" style={{ color: 'rgb(var(--c-coral))' }}>{drafts.length}</div>
        <div>
          <p className="text-[14px] font-bold text-text-primary">Draft{drafts.length !== 1 ? 's' : ''}</p>
          <p className="text-[12px] text-text-muted">From Magic Link</p>
        </div>
        <button
          onClick={() => navigate('/magic')}
          className="ml-auto px-4 py-2.5 rounded-[12px] text-[13px] font-bold text-white"
          style={{
            background: 'linear-gradient(135deg, rgb(var(--c-coral)), rgb(var(--c-coral-hover)))',
            boxShadow: 'var(--shadow-glow-coral)',
          }}
        >
          Open Magic Link
        </button>
      </div>

      {/* Search */}
      {drafts.length > 0 && (
        <div className="mb-6">
          <div
            className="flex items-center gap-3 px-4 py-3 rounded-[14px]"
            style={{
              background: 'rgba(255,255,255,0.04)',
              border: '1.5px solid var(--border-color)',
            }}
          >
            <MagnifyingGlassIcon className="w-5 h-5 text-text-muted flex-shrink-0" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Search drafts..."
              className="flex-1 bg-transparent text-[14px] text-text-primary focus:outline-none placeholder:text-text-muted"
            />
          </div>
        </div>
      )}

      {/* Loading */}
      {loading ? (
        <div className="flex flex-col items-center py-16">
          <div
            className="w-10 h-10 rounded-full border-2 animate-spin mb-4"
            style={{ borderColor: 'rgba(232,54,79,0.2)', borderTopColor: 'rgb(var(--c-coral))' }}
          />
          <p className="text-[14px] text-text-muted">Loading drafts...</p>
        </div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-16">
          <div className="text-[48px] mb-4 opacity-50">✨</div>
          <h3 className="text-[18px] font-bold text-text-primary mb-2">No Magic Link drafts</h3>
          <p className="text-[14px] text-text-secondary max-w-[300px] mx-auto">
            {searchQuery
              ? 'No drafts match your search.'
              : 'Posts generated by Magic Link that haven\'t been published will appear here.'}
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {filtered.map((draft) => {
            const platforms: PlatformType[] = Array.isArray(draft.platforms) ? draft.platforms : [];
            const title = draft.hook || draft.caption?.slice(0, 60) || 'Untitled Draft';

            return (
              <div
                key={draft.id}
                className="rounded-[16px] overflow-hidden transition-all duration-200"
                style={{
                  background: 'rgb(var(--c-bg-card))',
                  border: '1px solid var(--border-color)',
                }}
              >
                <div className="p-5">
                  {/* Top row: platform + date */}
                  <div className="flex items-center gap-2 mb-3">
                    <span
                      className="px-2.5 py-1 rounded-full text-[11px] font-bold"
                      style={{ background: 'rgba(232,54,79,0.1)', color: 'rgb(232,54,79)' }}
                    >
                      Magic Link
                    </span>
                    {platforms.map((p) => (
                      <span
                        key={p}
                        className="px-2 py-1 rounded-full text-[11px] font-semibold"
                        style={{ background: 'rgba(59,130,246,0.1)', color: 'rgb(var(--c-blue))' }}
                      >
                        {platformEmoji[p] || '📱'} {p.charAt(0).toUpperCase() + p.slice(1)}
                      </span>
                    ))}
                    <span className="ml-auto text-[11px] text-text-muted">
                      {draft.created_at ? format(new Date(draft.created_at), 'MMM d, yyyy') : ''}
                    </span>
                  </div>

                  {/* Media preview */}
                  {draft.media_files && draft.media_files.length > 0 && (
                    <div className="flex gap-2 mb-3">
                      {draft.media_files.slice(0, 3).map((url, idx) => (
                        <img
                          key={idx}
                          src={url}
                          alt=""
                          className="w-16 h-16 rounded-[10px] object-cover"
                          style={{ border: '1px solid var(--border-color)' }}
                        />
                      ))}
                      {draft.media_files.length > 3 && (
                        <div
                          className="w-16 h-16 rounded-[10px] flex items-center justify-center text-[12px] font-bold text-text-muted"
                          style={{ background: 'rgba(255,255,255,0.04)', border: '1px solid var(--border-color)' }}
                        >
                          +{draft.media_files.length - 3}
                        </div>
                      )}
                    </div>
                  )}

                  {/* Title */}
                  <h3 className="text-[15px] font-bold text-text-primary mb-2 line-clamp-1">
                    {title}
                  </h3>

                  {/* Caption preview */}
                  <p className="text-[13px] text-text-secondary line-clamp-2 leading-relaxed mb-4">
                    {draft.caption || 'No caption'}
                  </p>

                  {/* Actions */}
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => handleEdit(draft.id)}
                      className="flex items-center gap-1.5 px-3.5 py-2 rounded-[10px] text-[13px] font-semibold transition-all"
                      style={{
                        background: 'linear-gradient(135deg, rgb(var(--c-coral)), rgb(var(--c-coral-hover)))',
                        color: 'white',
                      }}
                    >
                      <PencilIcon className="w-3.5 h-3.5" />
                      Edit
                    </button>
                    <button
                      onClick={() => navigate('/magic')}
                      className="flex items-center gap-1.5 px-3.5 py-2 rounded-[10px] text-[13px] font-semibold transition-all"
                      style={{
                        background: 'rgba(255,255,255,0.06)',
                        border: '1px solid var(--border-color)',
                        color: 'rgb(var(--c-text-primary))',
                      }}
                    >
                      <SparklesIcon className="w-3.5 h-3.5" />
                      Resume in Magic Link
                    </button>
                    <button
                      onClick={() => handleDelete(draft.id)}
                      disabled={deletingId === draft.id}
                      className="ml-auto flex items-center gap-1.5 px-3 py-2 rounded-[10px] text-[13px] font-semibold transition-all"
                      style={{
                        color: 'rgb(239,68,68)',
                        opacity: deletingId === draft.id ? 0.5 : 1,
                      }}
                    >
                      <TrashIcon className="w-3.5 h-3.5" />
                      {deletingId === draft.id ? '...' : 'Delete'}
                    </button>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

export default MagicDraftPage;
