# Generated by Django 4.2.7 on 2026-01-21 13:18

import ai_video.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False, help_text='Available to all users')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('social_media', 'Social Media'), ('marketing', 'Marketing/Ads'), ('product', 'Product Demo'), ('intro_outro', 'Intro/Outro'), ('background', 'Background/Loop'), ('tutorial', 'Tutorial'), ('storytelling', 'Storytelling'), ('music_visual', 'Music Visual'), ('nature', 'Nature/Landscape'), ('abstract', 'Abstract/Art'), ('other', 'Other')], max_length=30)),
                ('prompt_template', models.TextField(help_text='Use {subject}, {style}, {action} as placeholders')),
                ('negative_prompt', models.TextField(blank=True, null=True)),
                ('recommended_style', models.CharField(choices=[('realistic', 'Realistic'), ('cinematic', 'Cinematic'), ('anime', 'Anime/Animation'), ('cartoon', 'Cartoon'), ('3d_animation', '3D Animation'), ('artistic', 'Artistic'), ('vintage', 'Vintage/Retro'), ('slow_motion', 'Slow Motion'), ('timelapse', 'Timelapse'), ('documentary', 'Documentary'), ('sci_fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('horror', 'Horror/Dark'), ('comedy', 'Comedy/Fun'), ('music_video', 'Music Video')], default='cinematic', max_length=30)),
                ('recommended_duration', models.IntegerField(choices=[(3, '3 seconds'), (5, '5 seconds'), (8, '8 seconds'), (10, '10 seconds'), (15, '15 seconds'), (30, '30 seconds')], default=5)),
                ('recommended_aspect_ratio', models.CharField(choices=[('16:9', '16:9 (Landscape)'), ('9:16', '9:16 (Portrait/Story)'), ('1:1', '1:1 (Square)'), ('4:3', '4:3 (Classic)'), ('21:9', '21:9 (Cinematic)')], default='16:9', max_length=10)),
                ('preview_thumbnail', models.ImageField(blank=True, null=True, upload_to='video_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VideoLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo_file', models.ImageField(upload_to=ai_video.models.logo_upload_path)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_logos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the video', max_length=200)),
                ('prompt', models.TextField(help_text='Detailed description for video generation')),
                ('negative_prompt', models.TextField(blank=True, help_text='What to avoid in the video', null=True)),
                ('style', models.CharField(choices=[('realistic', 'Realistic'), ('cinematic', 'Cinematic'), ('anime', 'Anime/Animation'), ('cartoon', 'Cartoon'), ('3d_animation', '3D Animation'), ('artistic', 'Artistic'), ('vintage', 'Vintage/Retro'), ('slow_motion', 'Slow Motion'), ('timelapse', 'Timelapse'), ('documentary', 'Documentary'), ('sci_fi', 'Sci-Fi'), ('fantasy', 'Fantasy'), ('horror', 'Horror/Dark'), ('comedy', 'Comedy/Fun'), ('music_video', 'Music Video')], default='realistic', max_length=30)),
                ('duration', models.IntegerField(choices=[(3, '3 seconds'), (5, '5 seconds'), (8, '8 seconds'), (10, '10 seconds'), (15, '15 seconds'), (30, '30 seconds')], default=5)),
                ('resolution', models.CharField(choices=[('480p', '480p (SD)'), ('720p', '720p (HD)'), ('1080p', '1080p (Full HD)'), ('4k', '4K (Ultra HD)')], default='1080p', max_length=20)),
                ('aspect_ratio', models.CharField(choices=[('16:9', '16:9 (Landscape)'), ('9:16', '9:16 (Portrait/Story)'), ('1:1', '1:1 (Square)'), ('4:3', '4:3 (Classic)'), ('21:9', '21:9 (Cinematic)')], default='16:9', max_length=10)),
                ('fps', models.IntegerField(choices=[(24, '24 FPS (Cinematic)'), (30, '30 FPS (Standard)'), (60, '60 FPS (Smooth)')], default=30)),
                ('logo_position', models.CharField(choices=[('none', 'No Logo'), ('top_left', 'Top Left'), ('top_right', 'Top Right'), ('top_center', 'Top Center'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right'), ('bottom_center', 'Bottom Center'), ('center', 'Center')], default='none', max_length=20)),
                ('logo_size', models.IntegerField(default=10, help_text='Logo size as percentage (5-25)')),
                ('logo_opacity', models.IntegerField(default=100, help_text='Logo opacity (10-100)')),
                ('seed', models.IntegerField(blank=True, help_text='Seed for reproducibility', null=True)),
                ('enhance_prompt', models.BooleanField(default=True, help_text='AI-enhance the prompt')),
                ('camera_motion', models.CharField(blank=True, choices=[('', 'Default'), ('static', 'Static (No Movement)'), ('pan_left', 'Pan Left'), ('pan_right', 'Pan Right'), ('tilt_up', 'Tilt Up'), ('tilt_down', 'Tilt Down'), ('zoom_in', 'Zoom In'), ('zoom_out', 'Zoom Out'), ('orbit', 'Orbit/Circle'), ('dolly', 'Dolly/Track'), ('crane', 'Crane Shot'), ('handheld', 'Handheld/Shaky')], max_length=50, null=True)),
                ('motion_intensity', models.CharField(blank=True, choices=[('', 'Default'), ('subtle', 'Subtle'), ('moderate', 'Moderate'), ('dynamic', 'Dynamic'), ('intense', 'Intense')], max_length=20, null=True)),
                ('generated_video', models.FileField(blank=True, null=True, upload_to=ai_video.models.generated_video_path)),
                ('generated_video_with_logo', models.FileField(blank=True, null=True, upload_to=ai_video.models.generated_video_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=ai_video.models.thumbnail_path)),
                ('enhanced_prompt', models.TextField(blank=True, help_text='AI-enhanced prompt used', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time', models.FloatField(default=0, help_text='Processing time in seconds')),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_video.videologo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Generation',
                'verbose_name_plural': 'Video Generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserVideoSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_gemini_api_key', models.TextField(blank=True, db_column='gemini_api_key', null=True)),
                ('default_style', models.CharField(choices=[('realistic', 'Realistic'), ('cinematic', 'Cinematic'), ('anime', 'Anime/Animation'), ('cartoon', 'Cartoon'), ('3d_animation', '3D Animation'), ('artistic', 'Artistic'), ('vintage', 'Vintage/Retro'), ('slow_motion', 'Slow Motion'), ('timelapse', 'Timelapse'), ('documentary', 'Documentary')], default='realistic', max_length=50)),
                ('default_duration', models.IntegerField(choices=[(3, '3 seconds'), (5, '5 seconds'), (8, '8 seconds'), (10, '10 seconds'), (15, '15 seconds')], default=5)),
                ('default_resolution', models.CharField(choices=[('480p', '480p (SD)'), ('720p', '720p (HD)'), ('1080p', '1080p (Full HD)'), ('4k', '4K (Ultra HD)')], default='1080p', max_length=20)),
                ('total_videos_generated', models.IntegerField(default=0)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('total_duration_generated', models.IntegerField(default=0, help_text='Total seconds of video generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Video Settings',
                'verbose_name_plural': 'User Video Settings',
            },
        ),
        migrations.CreateModel(
            name='SavedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to=ai_video.models.generated_video_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=ai_video.models.thumbnail_path)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_videos', to=settings.AUTH_USER_MODEL)),
                ('video_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ai_video.videogeneration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
