# Generated by Django 6.0.3 on 2026-04-29 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_video', '0002_add_reference_image'),
        ('brands', '0008_prompthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogeneration',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_generations', to='brands.brand'),
        ),
        migrations.AddField(
            model_name='videogeneration',
            name='brand_enhanced_prompt',
            field=models.TextField(blank=True, help_text='Prompt enhanced with BrandDNA context', null=True),
        ),
        migrations.AddField(
            model_name='videogeneration',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_generations', to='brands.workspace'),
        ),
    ]
