# Generated by Django 5.2.14 on 2026-05-24 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_video', '0003_videogeneration_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogeneration',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videogeneration',
            name='regenerated_from',
            field=models.ForeignKey(blank=True, help_text='The original VideoGeneration whose feedback spawned this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='ai_video.videogeneration'),
        ),
        migrations.AddField(
            model_name='videogeneration',
            name='user_feedback',
            field=models.TextField(blank=True, default='', help_text='What the user wants changed about this video'),
        ),
        migrations.AlterField(
            model_name='videogeneration',
            name='duration',
            field=models.IntegerField(choices=[(3, '3 seconds'), (5, '5 seconds'), (8, '8 seconds'), (10, '10 seconds'), (15, '15 seconds'), (30, '30 seconds')], default=8),
        ),
    ]
