# Generated by Django 4.2.7 on 2026-02-14 12:32

from django.db import migrations


def backfill_onboarding(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    OnboardingProgress = apps.get_model('onboarding', 'OnboardingProgress')
    from django.utils import timezone
    now = timezone.now()
    for user in User.objects.all():
        OnboardingProgress.objects.get_or_create(
            user=user,
            defaults={
                'current_step': 7,
                'completed_steps': [1, 2, 3, 4, 5, 6, 7],
                'is_completed': True,
                'completed_at': now,
            }
        )


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_onboarding, reverse_backfill),
    ]
