# Generated by Django 4.2.7 on 2025-12-20 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('telegram', 'Telegram')], max_length=20)),
                ('account_name', models.CharField(help_text='@username or page name', max_length=200)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('platform_data', models.TextField(default='{}', help_text='JSON data: page_id, api_keys, etc.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Token Expired'), ('invalid', 'Invalid Credentials'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_error', models.TextField(blank=True, null=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': 'Social Accounts',
                'db_table': 'social_accounts',
                'ordering': ['-connected_at'],
                'unique_together': {('user', 'platform', 'account_name')},
            },
        ),
    ]
