# Generated by Django 4.2.7 on 2025-12-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='platform_data',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='facebook_access_token',
            field=models.TextField(blank=True, help_text='Facebook Page Access Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='facebook_page_id',
            field=models.CharField(blank=True, help_text='Facebook Page ID', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='instagram_access_token',
            field=models.TextField(blank=True, help_text='Instagram Graph API Access Token (same as Facebook)', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='instagram_business_account_id',
            field=models.CharField(blank=True, help_text='Instagram Business Account ID', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='linkedin_access_token',
            field=models.TextField(blank=True, help_text='LinkedIn Access Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='linkedin_person_urn',
            field=models.CharField(blank=True, help_text='LinkedIn Person URN (from profile)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='pinterest_access_token',
            field=models.TextField(blank=True, help_text='Pinterest Access Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='pinterest_board_id',
            field=models.CharField(blank=True, help_text='Pinterest Board ID', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='telegram_bot_token',
            field=models.TextField(blank=True, help_text='Telegram Bot Token (from @BotFather)', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='telegram_channel_id',
            field=models.CharField(blank=True, help_text='Telegram Channel ID (e.g., @channel or -100123456)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='tiktok_access_token',
            field=models.TextField(blank=True, help_text='TikTok Access Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='tiktok_refresh_token',
            field=models.TextField(blank=True, help_text='TikTok Refresh Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='twitter_access_token',
            field=models.TextField(blank=True, help_text='Twitter Access Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='twitter_access_token_secret',
            field=models.TextField(blank=True, help_text='Twitter Access Token Secret', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='twitter_api_key',
            field=models.CharField(blank=True, help_text='Twitter API Key (Consumer Key)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='twitter_api_secret',
            field=models.CharField(blank=True, help_text='Twitter API Secret (Consumer Secret)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='youtube_access_token',
            field=models.TextField(blank=True, help_text='YouTube/Google Access Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='youtube_channel_id',
            field=models.CharField(blank=True, help_text='YouTube Channel ID', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='youtube_refresh_token',
            field=models.TextField(blank=True, help_text='YouTube/Google Refresh Token', null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='account_name',
            field=models.CharField(help_text='Display name or @username', max_length=200),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the access token expires', null=True),
        ),
    ]
