# Generated by Django 4.2.7 on 2026-02-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_remove_socialaccount_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('telegram', 'Telegram'), ('messenger', 'Facebook Messenger')], max_length=20),
        ),
    ]
