# Generated by Django 6.0.2 on 2026-04-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0004_oauthstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='linkedin_organization_urn',
            field=models.CharField(blank=True, help_text='LinkedIn Organization URN (urn:li:organization:xxx) for Company Page posting', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='linkedin_refresh_token',
            field=models.TextField(blank=True, help_text='LinkedIn Refresh Token (Community Management API only)', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='pinterest_refresh_token',
            field=models.TextField(blank=True, help_text='Pinterest Refresh Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='reddit_access_token',
            field=models.TextField(blank=True, help_text='Reddit Access Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='reddit_refresh_token',
            field=models.TextField(blank=True, help_text='Reddit Refresh Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='reddit_username',
            field=models.CharField(blank=True, help_text='Reddit Username (u/username)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='linkedin_person_urn',
            field=models.CharField(blank=True, help_text='LinkedIn Person URN (urn:li:person:xxx)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('telegram', 'Telegram'), ('messenger', 'Facebook Messenger')], max_length=20),
        ),
    ]
