# Generated by Django 5.2.14 on 2026-06-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0005_add_linkedin_reddit_pinterest_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='gbp_access_token',
            field=models.TextField(blank=True, help_text='Google Business Profile Access Token', null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='gbp_account_id',
            field=models.CharField(blank=True, help_text='GBP Account resource ID (accounts/{id})', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='gbp_location_id',
            field=models.CharField(blank=True, help_text='GBP Location resource ID (locations/{id})', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='gbp_location_name',
            field=models.CharField(blank=True, help_text='Human-readable business location name (e.g. "Seven Door Spa")', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='gbp_refresh_token',
            field=models.TextField(blank=True, help_text='Google Business Profile Refresh Token', null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('reddit', 'Reddit'), ('telegram', 'Telegram'), ('messenger', 'Facebook Messenger'), ('google_business', 'Google Business Profile')], max_length=20),
        ),
    ]
